/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xfsettingsd & #TOGLIERLO SE SI USA NWG-LOOK OPPURE SI USA XFT.DPI
dunst & #TOGLIERLO SE SI USA XFCE4-NOTIFYD
xsetroot -cursor_name left_ptr &
picom & #disattivare la vsync per sfarfallii
polybar &
waypaper --restore &
xrdb -merge /home/vito/.Xresources
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-xapp &
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY
exec bspwm
